"""initial tables

Revision ID: df9f64eaf1da
Revises: 
Create Date: 2018-02-04 04:35:27.192990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9f64eaf1da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcript',
    sa.Column('e_id', sa.String(length=23), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('path', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('e_id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('result',
    sa.Column('token', sa.CHAR(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('transcript_id', sa.String(length=23), nullable=True),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcript.e_id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('path', sa.String(length=120), nullable=True),
    sa.Column('ftype', sa.String(length=20), nullable=True),
    sa.Column('result_token', sa.CHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['result_token'], ['result.token'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    op.drop_table('result')
    op.drop_table('transcript')
    # ### end Alembic commands ###
